name: Java CI with Gradle

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        jdk: [ 'temurin', 'zulu', 'adoptopenjdk', 'corretto', 'oraclejdk' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution:  ${{ matrix.jdk }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10'

      - name: Build with Gradle
        run: gradle clean build

      - name: Test with Gradle
        run: gradle test
